//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkloadWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitTB
    {
        public int UnitID { get; set; }
        public string Unit { get; set; }
        public string Division { get; set; }
        public string ManagerID { get; set; }
        public Nullable<bool> UnitActive { get; set; }
    }
}
