//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkloadWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WeekTB
    {
        public int id { get; set; }
        public Nullable<int> year { get; set; }
        public Nullable<int> week { get; set; }
        public Nullable<System.DateTime> firstDate { get; set; }
        public Nullable<System.DateTime> lastDate { get; set; }
    }
}
