//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkloadWebApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkloadRecord
    {
        public int ID { get; set; }
        public string Username { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> ProjectID { get; set; }
        public Nullable<double> WorkloadWeek1 { get; set; }
        public Nullable<double> WorkloadWeek2 { get; set; }
        public Nullable<double> WorkloadWeek3 { get; set; }
        public Nullable<double> WorkloadWeek4 { get; set; }
        public Nullable<double> WorkloadWeek5 { get; set; }
        public Nullable<double> WorkloadWeek6 { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> CommitData { get; set; }
    }
}
