//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkloadWebApp.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkloadDBEntities : DbContext
    {
        public WorkloadDBEntities()
            : base("name=WorkloadDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EmployeeTB> EmployeeTBs { get; set; }
        public virtual DbSet<ProjectSelectionTB> ProjectSelectionTBs { get; set; }
        public virtual DbSet<ProjectTB> ProjectTBs { get; set; }
        public virtual DbSet<UnitTB> UnitTBs { get; set; }
        public virtual DbSet<C5dayHolidayTB> C5dayHolidayTB { get; set; }
        public virtual DbSet<C6dayHolidayTB> C6dayHolidayTB { get; set; }
        public virtual DbSet<RecordMonthTB> RecordMonthTBs { get; set; }
        public virtual DbSet<WeekTB> WeekTBs { get; set; }
        public virtual DbSet<WorkloadRecordTB> WorkloadRecordTBs { get; set; }
        public virtual DbSet<ReportMonthTB> ReportMonthTBs { get; set; }
    }
}
